import path from "path";
import fs from "fs";
import { getHistoryDb } from "./historyStore";
import { classifyWithLlm } from "./llmClassifier.service";

export interface HsCodeEntry { code: string; section: string; description: string; parent: string; level: number; }
export interface SuggestionEntry { code: string; description: string; description_cn: string; confidence: number; matched_keywords: string[]; }
export interface HsCodeLookupResult { valid: boolean; format_valid: boolean; code: string; description: string | null; chapter: string; level: number; }
export interface HsCodeMatchResult { matched: boolean; confidence: "exact"|"partial"|"mismatch"|"unknown"; detail: string; suggestions: SuggestionEntry[]; suggested_description: string|null; }

export function ensureHsCodeTable(): void {
  const db = getHistoryDb();
  if (db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='hs_codes'").get()) return;
  db.exec("CREATE TABLE hs_codes (code TEXT PRIMARY KEY, section TEXT NOT NULL, description TEXT NOT NULL, parent TEXT, level INTEGER NOT NULL)");
  db.exec("CREATE INDEX IF NOT EXISTS idx_hs_codes_parent ON hs_codes(parent)");
  const csvPath = path.resolve(__dirname, "../../data/hs_codes.csv");
  if (!fs.existsSync(csvPath)) return;
  const content = fs.readFileSync(csvPath, "utf-8");
  const lines = content.trim().split("\n"); if (lines.length < 2) return;
  const insert = db.prepare("INSERT OR IGNORE INTO hs_codes (code, section, description, parent, level) VALUES (?, ?, ?, ?, ?)");
  db.transaction(() => { for (let i=1; i<lines.length; i++) { const line=lines[i].trim(); if(!line) continue; const parts=line.split(","); if(parts.length<5) continue; insert.run(parts[1], parts[0], parts.slice(2,parts.length-2).join(",").replace(/^\"/,"").replace(/\"$/,""), parts[parts.length-2], String(parseInt(parts[parts.length-1],10))); } })();
}

function expandSearchCode(code: string): string[] { const codes=[code]; if(code.length>2)codes.push(code.substring(0,2)); if(code.length>=4)codes.push(code.substring(0,4)); return codes; }

export function validateHsCode(code: string): HsCodeLookupResult {
  const cleaned=code.replace(/[.\-\s]/g,""); const formatValid=/^\d{4,10}$/.test(cleaned);
  if(!formatValid) return {valid:false,format_valid:false,code:cleaned,description:null,chapter:"",level:0};
  const db=getHistoryDb();
  for(const c of expandSearchCode(cleaned).reverse()) { const row=db.prepare("SELECT * FROM hs_codes WHERE code=?").get(c) as HsCodeEntry|undefined; if(row) return {valid:true,format_valid:true,code:c,description:row.description,chapter:c.substring(0,2),level:row.level}; }
  return {valid:false,format_valid:true,code:cleaned.substring(0,6),description:null,chapter:cleaned.substring(0,2),level:0};
}

export function lookupHsCode(code: string): HsCodeEntry|null {
  const db=getHistoryDb(); const cleaned=code.replace(/[.\-\s]/g,"");
  return (db.prepare("SELECT * FROM hs_codes WHERE code=?").get(cleaned.substring(0,6)) as HsCodeEntry|undefined)||null;
}

// SYNONYM MAP (English -> HS terms, ONLY for product descriptions)
const SYNONYM_MAP: Record<string,string[]> = {
  laptop:["portable","automatic","data","processing"],computer:["automatic","data","processing","machine"],
  phone:["telephone","cellular"],tablet:["portable","automatic","data","processing"],
  monitor:["display","screen"],keyboard:["input","peripheral"],mouse:["input","peripheral"],
  printer:["printing","output"],camera:["photographic","digital"],speaker:["loudspeaker","audio"],
  headphone:["earphone","audio"],television:["television","reception","display"],
  shirt:["clothing","garment","apparel"],pants:["clothing","garment","trousers"],
  jacket:["clothing","garment","coat"],shoes:["footwear","shoe"],toy:["toy","game","recreational"],
  doll:["doll","toy"],book:["printed","book"],paper:["paper","cellulose"],
  plastic:["plastic","polymer"],wooden:["wood","furniture"],steel:["steel","iron","metal"],
  aluminum:["aluminium","metal"],copper:["copper","metal"],glass:["glass","glassware"],
  ceramic:["ceramic","porcelain"],furniture:["furniture","seat"],chair:["chair","seat","furniture"],
  table:["table","furniture"],lamp:["lamp","lighting"],battery:["battery","accumulator"],
  motor:["motor"],pump:["pump","liquid"],valve:["valve","tap"],bearing:["bearing","ball"],
  cable:["cable","wire","insulated"],tool:["tool","hand","implement"],knife:["knife","blade","cutting"],
  watch:["watch","clock"],jewelry:["jewelry","precious","metal"],ring:["ring","jewelry"],
  food:["food","edible"],drink:["beverage","drink"],wine:["wine","grape","fermented"],
  cosmetic:["cosmetic","beauty","makeup"],perfume:["perfume","fragrance"],
  medicine:["medicament","pharmaceutical"],vitamin:["vitamin","supplement"],
  basketball:["ball","sports","athletic"],football:["ball","sports"],bicycle:["bicycle","cycle","vehicle"],
  car:["car","automobile","vehicle"],men:["men","male"],women:["women","female"],
  male:["male","men"],female:["female","women"],boy:["boy","children","male"],
  girl:["girl","children","female"],child:["child","children","kids"],baby:["baby","infant"],
  cotton:["cotton","textile"],silk:["silk","textile"],wool:["wool","textile"],
  knit:["knit","knitted"],woven:["woven","weave"],stroller:["baby","carriage","pushchair","perambulator"],
"活动物":["horses","asses","mules","hinnies"],
"食用肉":["meat","bovine","animals","fresh"],
"水产鱼虾":["fish","live"],
"乳品蛋蜜":["milk","cream","concentrated","containing"],
"动物副产品":["human","hair","unworked","whether"],
"植物花木":["bulbs","tubers","tuberous","roots"],
"食用蔬菜":["potatoes","fresh","chilled"],
"食用水果":["nuts","edible","coconuts","brazil"],
"咖啡茶叶":["coffee","whether","roasted","decaffeinated"],
"谷物粮食":["wheat","meslin"],
"制粉工业":["wheat","meslin","flour"],
"油籽药材":["soya","beans","whether","broken"],
"树胶树脂":["lac","natural","gums","resins"],
"编织材料":["vegetable","materials","kind","used"],
"动植物油":["pig","fat","including","lard"],
"肉类制品":["sausages","similar","products","meat"],
"糖果制品":["cane","beet","sugar","chemically"],
"可可制品":["cocoa","beans","whole","broken"],
"粮食制品":["malt","extract","flour","groats"],
"蔬菜制品":["vegetables","fruit","nuts","edible"],
"调味制品":["extracts","essences","concentrates","coffee"],
"饮料酒醋":["waters","including","natural","artificial"],
"饲料残渣":["flours","meal","pellets","meat"],
"烟草制品":["tobacco","unmanufactured","tobacco","refuse"],
"盐硫矿产":["salt","including","table","salt"],
"矿物矿砂":["iron","ores","concentrates","including"],
"矿物燃料":["coal","briquettes","ovoids","similar"],
"无机化工":["fluorine","chlorine","bromine","iodine"],
"有机化工":["acyclic","hydrocarbons"],
"医药用品":["glands","organs","extracts","secretions"],
"肥料":["fertilizers","animal","vegetable","whether"],
"染料颜料":["tanning","extracts","vegetable","origin"],
"香精化妆":["oils","essential","concretes","absolutes"],
"肥皂洗涤":["soap","organic","surface","active"],
"蛋白胶黏":["casein","caseinates","casein","derivatives"],
"炸药烟火":["explosives","propellent","powders"],
"感光照相":["photographic","plates","film","flat"],
"杂项化工":["artificial","graphite","colloidal","semi"],
"塑料制品":["polymers","ethylene","primary","forms"],
"橡胶制品":["natural","rubber","balata","gutta"],
"生皮毛皮":["raw","hides","skins","bovine"],
"皮革箱包":["saddlery","harness","animal","including"],
"毛皮制品":["raw","furskins","including","heads"],
"木材制品":["fuel","wood","logs","billets"],
"软木制品":["natural","cork","raw","simply"],
"编织制品":["plaits","similar","products","plaiting"],
"纸浆":["wood","pulp","mechanical","wood"],
"纸张制品":["newsprint","rolls","sheets"],
"印刷书籍":["printed","books","brochures","leaflets"],
"丝绸原料":["silk","worm","cocoons","suitable"],
"羊毛原料":["wool","carded","combed"],
"棉花原料":["cotton","carded","combed"],
"植物纤维":["flax","raw","processed","spun"],
"化纤长丝":["sewing","thread","man","made"],
"化纤短纤":["synthetic","filament","tow"],
"絮胎毡呢":["wadding","textile","materials","articles"],
"地毯铺地":["carpets","textile","floor","coverings"],
"特种织物":["fabrics","woven","pile","chenille"],
"涂覆织物":["textile","fabrics","gum","amylaceous"],
"针织面料":["fabrics","pile","fabrics","including"],
"针织服装":["coats","men","boys","overcoats"],
"梭织服装":["overcoats","car","coats","capes"],
"纺织成品":["blankets","travelling","rugs"],
"鞋靴护腿":["footwear","waterproof","outer","soles"],
"帽子头饰":["hat","forms","hat","bodies"],
"伞杖鞭子":["umbrellas","sun","umbrellas","including"],
"羽毛人发":["skin","parts","birds","their"],
"石材制品":["stone","setts","curbstones","flagstones"],
"陶瓷制品":["bricks","blocks","tiles","ceramic"],
"玻璃制品":["glass","cullet","waste","scrap"],
"珠宝贵金":["pearls","natural","cultured","whether"],
"钢铁":["pig","iron","spiegeleisen","pigs"],
"钢铁制品":["iron","steel","sheet","piling"],
"铜镍制品":["copper","mattes","cement","copper"],
"镍制品":["nickel","mattes","nickel","oxide"],
"铝制品":["aluminium","unwrought"],
"铅制品":["lead","unwrought"],
"锌制品":["zinc","unwrought"],
"锡制品":["tin","unwrought"],
"其他贱金":["tungsten","wolfram","articles","thereof"],
"金属工具":["tools","hand","spades","shovels"],
"金属杂件":["padlocks","locks","key","combination"],
"核能机械":["nuclear","reactors","fuel","elements"],
"电子电器":["electric","motors","generators","excluding"],
"铁路机车":["rail","locomotives","powered","external"],
"汽车零件":["tractors","tractors","heading","8709"],
"航空航天":["balloons","dirigibles","gliders","hang"],
"船舶航运":["cruise","ships","excursion","boats"],
"仪器仪表":["optical","fibres","optical","fibre"],
"钟表计时":["wrist","watches","pocket","watches"],
"乐器音响":["pianos","including","automatic","pianos"],
"武器弹药":["military","weapons","revolvers","pistols"],
"家具寝具":["seats","those","heading","9402"],
"玩具运动":["tricycles","scooters","pedal","cars"],
"杂项制品":["ivory","bone","tortoise","shell"],
"艺术品":["paintings","drawings","pastels","executed"],
"第99类":["commodities","specified","according","kind"]
};

// CHINESE TERM MAP (Chinese product terms -> English HS keywords)
const CN_MAP: Record<string,string[]> = {
  "牛肉":["beef","meat"],"猪肉":["pork","meat"],"鸡肉":["chicken","poultry"],"羊肉":["lamb","meat"],
  "鱼肉":["fish","fillet"],"虾":["shrimp","crustacean"],"蟹":["crab"],"龙虾":["lobster"],
  "三文鱼":["salmon","fish"],"牛奶":["milk","dairy"],"奶酪":["cheese","dairy"],"黄油":["butter"],
  "酸奶":["yogurt"],"鸡蛋":["egg"],"蜂蜜":["honey"],"蔬菜":["vegetable"],"水果":["fruit"],
  "苹果":["apple"],"香蕉":["banana"],"橙":["orange","citrus"],"葡萄":["grape"],
  "咖啡":["coffee","roasted"],"茶叶":["tea","leaf"],"大米":["rice","cereal"],"面粉":["flour","wheat"],
  "面条":["pasta","noodle"],"面包":["bread","bakery"],"巧克力":["chocolate","cocoa"],
  "糖果":["candy","sugar"],"饼干":["biscuit"],"罐头":["canned","preserved"],
  "果汁":["juice","fruit"],"矿泉水":["water","mineral"],"啤酒":["beer","malt"],
  "葡萄酒":["wine","grape"],"白酒":["spirit","alcohol"],"酱油":["sauce","soy"],
  "调味料":["seasoning","sauce"],"零食":["snack","food"],"宠物食品":["pet","food"],
  "药品":["medicine","pharmaceutical"],"维生素":["vitamin"],"化妆品":["cosmetic","beauty"],
  "口红":["lipstick"],"香水":["perfume","fragrance"],"护肤品":["skincare","cream"],
  "洗发水":["shampoo","hair"],"沐浴露":["body","wash"],"牙膏":["toothpaste"],"肥皂":["soap"],
  "洗衣液":["detergent","laundry"],"胶水":["glue","adhesive"],"蜡烛":["candle"],
  "塑料袋":["plastic","bag"],"塑料盒":["plastic","box"],"塑料瓶":["plastic","bottle"],
  "橡胶手套":["rubber","glove"],"轮胎":["tyre","rubber"],"皮包":["leather","handbag"],
  "钱包":["wallet","leather"],"皮带":["belt","leather"],"行李箱":["suitcase","luggage"],
  "背包":["backpack","rucksack"],"挎包":["bag","handbag","shoulder"],
  "双肩包":["backpack","bag","school"],"腰包":["bag","waist","pouch"],
  "包":["bag","case","container"],"木板":["wood","board"],"纸箱":["carton","box","paper"],
  "书籍":["book","printed"],"杂志":["magazine"],"标签":["label","paper"],"贴纸":["sticker"],
  "棉布":["cotton","fabric"],"丝绸":["silk","fabric"],"羊毛":["wool","textile"],
  "涤纶":["polyester"],  "尼龙":["nylon"],"T恤":["shirt","garment"],
  "衬衫":["shirt","blouse"],"上衣":["shirt","blouse","top"],"外套":["coat","jacket"],
  "夹克":["jacket"],"裤子":["pants","trousers"],"牛仔裤":["jeans","denim"],"裙":["skirt"],
  "连衣裙":["dress"],"毛衣":["sweater","knitwear"],"内衣":["underwear","lingerie"],
  "袜子":["socks","hosiery"],"泳装":["swimwear"],"睡衣":["pajamas","sleepwear"],
  "帽子":["hat","cap"],"围巾":["scarf"],"手套":["gloves"],"领带":["tie"],
  "运动服":["sportswear"],"雨衣":["raincoat","waterproof"],"羽绒服":["down","padded"],
  "床上用品":["bedding","linen"],"被子":["quilt"],"枕头":["pillow"],"毛巾":["towel"],
  "地毯":["carpet","rug"],"窗帘":["curtain"],"鞋":["shoes","footwear"],
  "运动鞋":["sneaker","sports"],"皮鞋":["leather","shoes"],"凉鞋":["sandal"],
  "拖鞋":["slipper"],"靴":["boot"],"雨伞":["umbrella"],"陶瓷":["ceramic","porcelain"],
  "瓷砖":["tile","ceramic"],"玻璃杯":["glass","cup"],"镜子":["mirror","glass"],
  "首饰":["jewelry"],"项链":["necklace"],"戒指":["ring"],"耳环":["earring"],"手链":["bracelet"],
  "钢材":["steel","metal"],"铝":["aluminum","metal"],"铜":["copper","metal"],
  "刀具":["knife","cutlery"],"螺丝":["screw","bolt"],"钉子":["nail","fastener"],
  "锁":["lock","padlock"],"工具":["tool"],"扳手":["wrench","tool"],"锤子":["hammer","tool"],
  "螺丝刀":["screwdriver"],"钳子":["plier"],"电脑":["computer","laptop"],
  "笔记本":["laptop","portable"],"平板":["tablet","portable"],"手机":["phone","smartphone"],
  "耳机":["headphone","earphone"],"音箱":["speaker","loudspeaker"],"麦克风":["microphone"],
  "键盘":["keyboard","peripheral"],"鼠标":["mouse","peripheral"],"显示器":["monitor","display"],
  "电视":["television","display"],"相机":["camera","photographic"],"摄像机":["camcorder","video"],
  "打印机":["printer"],"扫描仪":["scanner"],"投影仪":["projector"],
  "路由器":["router","network"],"硬盘":["disk","drive","storage"],"U盘":["usb","flash"],
  "芯片":["chip","circuit"],"电池":["battery","cell"],"充电宝":["power","bank"],
  "充电器":["charger","adapter"],"数据线":["cable","usb"],"电源":["power","adapter"],
  "灯泡":["bulb","LED","lamp"],"灯":["lamp","lighting"],"空调":["air","conditioner"],
  "冰箱":["refrigerator"],"洗衣机":["washing","machine"],"微波炉":["microwave","oven"],
  "吹风机":["hair","dryer"],"剃须刀":["shaver","razor"],  "吸尘器":["vacuum"],
  "电风扇":["fan","ventilating","blades","rotary"],
  "风扇":["fan","ventilating","blades"],
  "电扇":["fan","ventilating","blades"],
  "汽车":["car","automobile"],"摩托车":["motorcycle"],"自行车":["bicycle","cycle"],
  "电动自行车":["electric","bicycle"],"滑板车":["scooter"],"婴儿车":["stroller","baby"],
  "眼镜":["glasses","optical"],"太阳镜":["sunglasses"],"温度计":["thermometer"],
  "显微镜":["microscope"],"望远镜":["telescope","binoculars"],
  "吉他":["guitar","musical"],"钢琴":["piano","keyboard"],"小提琴":["violin"],"鼓":["drum"],
  "家具":["furniture"],"椅子":["chair","seat"],"桌子":["table","desk"],
  "沙发":["sofa","couch"],"床":["bed","frame"],"床垫":["mattress"],
  "柜子":["cabinet"],"书架":["bookshelf","shelf"],"灯具":["lamp","lighting"],
  "玩具":["toy","game"],"玩偶":["doll"],"拼图":["puzzle"],"积木":["block","building"],
  "运动器材":["sports","equipment"],"跑步机":["treadmill"],"哑铃":["dumbbell"],
  "瑜伽垫":["yoga","mat"],"帐篷":["tent","camping"],"渔具":["fishing","tackle"],
  "笔":["pen","writing"],"铅笔":["pencil"],"文具":["stationery"],
  "打火机":["lighter"],"拉链":["zipper"],"纽扣":["button"],"手表":["watch","timepiece"],
  "拖把":["mop","broom","brush","cleaning","floor","squeegee"],
  "扫把":["broom","brush","cleaning","sweeper","floor"],
  "抹布":["cloth","wipe","cleaning"],"清洁":["cleaning"],
  "无纺布":["nonwoven"],
  "垃圾桶":["bin","waste","container"],
  "收纳盒":["box","storage","container"],
  "晾衣架":["rack","drying","hanger"],
  "水壶":["kettle","water","bottle","flask","vacuum","thermos"],
  "保温杯":["vacuum","flask","cup"],"保温":["vacuum","insulated"],
  "水杯":["water","cup","bottle","drinking"],
  "杯子":["cup","mug","drinking","glass"],
  "咖啡壶":["coffee","maker","pot","kettle"],
  "茶壶":["teapot","tea","pot","ceramic"],
  "男士":["men","male"],"女士":["women","female"],"男":["men"],"女":["women"],
  "儿童":["children","kids"],"婴儿":["baby","infant"],"男孩":["boy"],"女孩":["girl"],
  "纯棉":["cotton","textile"],"棉":["cotton"],"真丝":["silk"],"麻":["linen"],
  "皮革":["leather"],"皮":["leather"],"塑料":["plastic","polymer"],"橡胶":["rubber"],
  "不锈钢":["stainless"],"金属":["metal"],"木":["wood"],"竹":["bamboo"],
  "玻璃":["glass"],"针织":["knit","knitted"],"梭织":["woven","weave"],
  "冷冻":["frozen"],"冷藏":["chilled"],"即食":["ready","instant"],"风干":["dried"],"腌制":["pickled","preserved"],
  "防水":["waterproof"],"防风":["windproof"],  "保暖":["warm","insulated"],
  "长袖":["long","sleeve"],"短袖":["short","sleeve"],"无袖":["sleeveless"],"运动":["sports","athletic"],
  "无线":["wireless","bluetooth"],"蓝牙":["bluetooth"],"USB":["usb"],"充电":["rechargeable"],
  "便携":["portable"],"智能":["smart"],"高清":["high","definition"],"4K":["4k","ultra"],"5G":["5g"],
  "处理器":["processor","cpu","computer","electronic"],"内存":["memory","ram","computer"],
  "固态":["solid","state","drive","storage"],"显卡":["graphics","video","computer"],
  "主板":["motherboard","computer"],"屏幕":["screen","display","monitor"],
  // Material (6-dimension)
  "ABS":["abs","plastic","polymer"],"真皮":["genuine","leather"],
  "纯羊毛":["pure","wool"],"羊绒":["cashmere","wool"],
  "记忆棉":["memory","foam","cushion"],"乳胶":["latex","rubber"],
  "碳纤维":["carbon","fiber","composite"],"铝合金":["aluminum","alloy","metal"],
  "钛合金":["titanium","alloy","metal"],"锌合金":["zinc","alloy","metal"],
  "硅胶":["silicone","rubber"],"亚克力":["acrylic","plastic"],
  "密度板":["mdf","fiberboard","wood"],"实木":["solid","wood"],
  "PU":["polyurethane","synthetic","leather"],
  // Processing (6-dimension)
  "手工制作":["handmade","handcrafted"],"手工":["handmade"],
  "CNC":["cnc","precision","machined"],"机加工":["machined"],
  "注塑":["injection","molded"],"吹塑":["blow","molded"],
  "冲压":["stamped","pressed"],"铸造":["cast"],
  "打磨":["polished"],"电镀":["electroplated","plated"],
  "烤漆":["baked","painted","coating"],"喷漆":["spray","painted"],
  "阳极氧化":["anodized"],"热处理":["heat","treated"],
  "组装":["assembled"],"模块化":["modular"],
  // Structure (6-dimension)
  "圆领":["round","neck","collar"],"V领":["v","neck"],
  "套头":["pullover","pull"],"开衫":["cardigan","open","front"],
  "翻盖":["clamshell","flip"],"折叠":["foldable"],
  "可拆卸":["detachable","removable"],"伸缩":["telescopic","extendable"],
  "旋转":["rotary","rotating","swivel"],"推拉":["sliding","push","pull"],
  "按压":["press","pump"],"电动":["electric","motorized"],
  "手动":["manual","hand"],"自动":["automatic"],
  "便携式":["portable"],"落地式":["floor","standing"],
  "壁挂式":["wall","mounted"],"嵌入式":["built","in","embedded"],
  "桌面式":["desktop","tabletop"],"手持式":["handheld"],
  "背光":["backlit","illuminated"],"双层":["double","layer"],
  // Composition numbers (6-dimension - keyword boost only)
  "100%":[],"95%":[],"90%":[],"80%":[],"75%":[],"70%":[],"65%":[],"60%":[],
  "50%":[],"30%":[],"25%":[],"20%":[],"10%":[],"5%":[],
"眼罩":["eye","mask"],
"鞋垫":["insoles"],
"假发":["wig"],
"潜水服":["wetsuit","diving","rubber","garment","knitted","apparel"],
"围裙（棉）":["apron","cotton"],
"围裙（人造纤维）":["apron","man","fibers"],
"襁褓":["swaddle"],
"和服带":["belt"],
"纺织品（丝绸）":["textile","fabric","silk"],
"纺织品（羊毛等）":["textile","fabric","wool","others"],
"纺织品（棉）":["textile","fabric","cotton"],
"纺织品（人造纤维）":["textile","fabric","man","fibers"],
"纱布手帕":["gauze","handkerchief"],
"开襟衫（男式 羊毛）":["cardigan","men","wool"],
"开襟衫（男式 羊绒毛）":["cardigan","men","cashmere"],
"开襟衫（男式 棉）":["cardigan","men","cotton"],
"开襟衫（男式 人造纤维）":["cardigan","men","man","fibers"],
"开襟衫（男式 其他纤维材料）":["cardigan","men","textile","materials"],
"开襟衫（女式 羊毛）":["cardigan","women","wool"],
"开襟衫（女式 羊绒毛）":["cardigan","women","cashmere"],
"开襟衫（女式 棉）":["cardigan","women","cotton"],
"开襟衫（女式 人造纤维）":["cardigan","women","man","fibers"],
"开襟衫（女式 其他纤维材料）":["cardigan","women","textile","materials"],
"发箍":["headband"],
"割烹着（日式罩衣）（棉）":["apron","cotton"],
"割烹着（日式罩衣）（人造纤维）":["apron","man","fibers"],
"头盔":["japanese","helmet"],
"发簪":["hairpin"],
"杏仁":["almond"],
"杏仁奶":["almond","milk"],
"青汁（含糖食品）":["green","juice","containing","added"],
"青汁（不含糖食品）":["green","juice","containing","added"],
"青海苔":["green","laver"],
"红豆":["red","bean"],
"甘栗":["baked","chestnut"],
"膨化米花":["rice","cracker"],
"酒精湿巾":["alcohol","tissue"],
"铝箔":["aluminum","foil"],
"泡盛":["awamori","liquor"],
"豆馅":["sweet","bean","paste"],
"炸红薯条":["sweet","potato","snack"],
"速食咖喱":["instant","curry"],
"速溶咖啡":["instant","coffee"],
"速溶汤":["instant","soup"],
"速溶茶":["instant","tea"],
"方便面":["instant","noodle"],
"乌龙茶":["oolong","tea"],
"威化饼干":["wafer"],
"威化饼干（以巧克力包覆食品）":["wafer","covered","chocolate"],
"伏特加":["vodka"],
"乌冬面":["wheat","noodle"],
"海胆":["sea","urchin","egg"],
"梅干":["pickled","plum"],
"原声吉他":["acoustic","guitar"],
"压缩袋":["compression","bag"],
"织针":["knitting","needles"],
"影集":["album"],
"安全别针":["safety","pin"],
"骨灰":["ashes"],
"湿纸巾":["wet","wipes"],
"羽绒被":["down","quilt"],
"绘画":["picture"],
"机械硬盘":["hdd"],
"液体肥皂":["liquid","soap"],
"固态硬盘":["ssd"],
"效果器":["effector"],
"徽章":["emblem"],
"装饰品（塑料制）":["ornament","plastic"],
"座钟":["clock"],
"装饰品（木制）":["ornament","wood"],
"装饰品（陶瓷制）":["ornament","ceramic"],
"婴儿湿巾":["baby","wipes"],
"护身符":["talisman"],
"纸尿裤":["diaper"],
"折叠伞":["folding","umbrella"],
"窗帘（合成纤维）":["curtain","synthetic","fibers"],
"窗帘（棉）":["curtain","cotton"],
"窗帘（羊毛）":["curtain","wool"],
"窗帘（其他材料）":["curtain"],
"IH电磁炉":["cooking","heater"],
"熨斗":["clothing","iron"],
"适配器":["adapter"],
"放大器":["amplifier"],
"即时成像相机":["instant","camera"],
"团扇":["round","fan"],
"AC适配器":["adapter"],
"SD卡":["card"],
"LED灯":["led","light"],
"黑胶唱片":["record"],
"电吉他":["electronic","guitar"],
"电贝司":["electronic","bass"],
"烤箱":["oven"],
"煤油取暖器":["oil","heater"],
"音乐播放器":["music","player"],
"手电筒":["flashlight"],
"加湿器":["humidifier"],
"盒式播放机":["cassette","player","portable"],
"照相机":["camera"],
"干电池（碱性）":["dry","cell","battery","alkaline"],
"干电池（碳性）":["dry","cell","battery","zinc"],
"空气净化器":["air","purifier"],
"转换插头":["travel","plug","adapter"],
"SIM卡":["sim","card"],
"地毯（纺织品）":["carpet","woven"],
"亚克力立牌":["acrylic","stand","figure"],
"独轮车":["unicycle"],
"鱼漂":["float"],
"游泳圈":["float"],
"备用调节器（潜水用品）":["scuba","diving","octopus"],
"沙包":["juggling","ball"],
"沉子":["weight"],
"八音盒":["music","box"],
"卡片":["card"],
"卡盒":["card","case"],
"纸牌游戏":["playing","card"],
"卡套":["card","sleeve"],
"乐器玩具":["musical","toy"],
"登山扣":["carabiner"],
"别针徽章":["can","badges"],
"钥匙圈":["key","holder"],
"手套（棒球用）":["baseball","glove"],
"圣诞树":["christmas","trees"],
"圣诞花环":["christmas","wreaths"],
"游戏卡带":["video","game","cartridge"],
"游戏机":["game","machine"],
"游戏光盘":["video","game","software"],
"便携式游戏机":["portable","game","machine"],
"剑玉":["juggling","toy"],
"鲤鱼旗":["koinobori"],
"高尔夫球杆":["golf","club"],
"高尔夫球杆身":["golf","club","shaft"],
"高尔夫球":["golf","ball"],
"游戏手柄":["controller"],
"冲浪板":["surfboard"],
"眼影":["eyeshadow"],
"眉笔":["eyebrow","pencil"],
"眼线笔":["eyeliner"],
"睫毛夹":["eyelash","curler"],
"粉饼":["face","powder"],
"卸妆油":["cleansing","oil"],
"卸妆膏":["cleansing","cream"],
"卸妆水":["make","remover"],
"妆前乳":["makeup","primer"],
"爽肤水":["skin","lotion"],
"【原则上无法受理】香水":["acceptable","general","perfume"],
"遮瑕膏":["concealer"],
"隐形眼镜洗液":["contact","lens","cleansers"],
"护发素":["hair","conditioner"],
"CC霜":["cream"],
"护肤霜":["skin","cream"],
"洗面奶":["face","wash"],
"棒香":["incense","stick"],
"腮红":["blusher"],
"假睫毛":["false","eyelashe"],
"指甲钳":["nail","clipper"],
"牙线":["dental","floss"],
"亮油":["top","coat"],
"头发护理产品（焗油膏、发膜等）":["hair","treatment","products"],
"乳液":["milky","lotion"],
"沐浴剂":["bath","powder"],
"护甲油":["nail","oil"],
"阿司匹林":["aspirin"],
"胃药":["stomach","medicine"],
"肠胃药":["digestive","medicine"],
"牌位":["mortuary","tablet"],
"感冒药":["medicine","cold"],
"蚊香":["mosquito","coil"],
"美瞳":["colored","contact","lenses"],
"中药":["chinese","medicine"],
"提神饮料":["tonic","medicine"],
"泻药":["laxative"],
"血压计":["blood","pressure","meter"],
"解热镇痛剂":["antifebrile","medicine"],
"止泻药":["medicine","diarrhea"],
"检测试剂盒":["diagnostic","kit"],
"抗生素":["antibiotic"],
"隐形眼镜":["contact","lens"],
"隐形眼镜保存液":["saline","solution","contact","lens"],
"杀虫药":["insecticide"],
"牙间刷":["interdental","brush"],
"膏药":["cold","compress"],
"【原则上无法受理】消毒剂":["acceptable","general","disinfectant"],
"安眠药":["sleeping","pill"],
"头痛药":["headache","medicine"],
"卫生棉垫":["sanitary","towel"],
"咳嗽药":["cough","medicine"],
"抱枕":["swaddling","pillows"],
"止痛药":["painkiller"],
"电动牙刷":["electric","toothbrush"],
"卫生巾":["sanitary","towel"],
"软膏":["ointment"],
"绘本":["picture","book"],
"护符":["talisman"],
"指南书":["guidebook"],
"会报":["newsletter"],
"乐谱":["music","score"],
"画册":["art","book"],
"目录簿":["catalog"],
"学报":["academic","journal"],
"日历":["calendar"],
"邮票":["stamp"],
"帆布、画布":["canvas"],
"教科书":["textbook"],
"发声书":["sound","book"],
"书签":["bookmark"],
"词典":["dictionary"],
"儿童书":["child","book"],
"照片":["photo"],
"照片集":["photo","book"],
"报纸":["newspaper"],
"地球仪":["world","globe"],
"地图":["map"],
"地图册":["map","book"],
"宣传单":["leaflet"],
"函授教育教材":["text","correspondence","study"],
"涂色画":["coloring","book"],
"印章":["stamp"],
"宣传手册":["pamphlet"],
"小册子":["booklet"],
"长柄大勺":["ladle"],
"猪口杯（日式酒盅）":["cup"],
"刮痧":["massage","plate"],
"美工刀":["cutter","knife"],
"西方餐具":["cutlery"],
"开罐器":["can","opener"],
"厨房用刀":["kitchen","knife"],
"金鱼缸":["goldfish","bowl"],
"耐油纸":["cooking","sheet"],
"杯垫（布制）":["coaster","fabric"],
"杯垫（木制）":["coaster","wood"],
"杯子（塑料制）":["cup","plastic"],
"杯子（玻璃制）":["cup","glass"],
"菜箸（烹饪、分餐用的长筷子）":["vegetable","chopsticks"],
"作务衣（日式工作服）（棉）":["japanese","traditional","workwear","cotton"],
"作务衣（日式工作服）（合成纤维）":["japanese","traditional","workwear","synthetic"],
"碟子":["dish"],
"饭勺":["rice","scoop"],
"香槟杯":["champagne","glasses"],
"餐具（陶制）":["tableware","pottery"],
"餐具（玻璃制）":["tableware","glass"],
"餐具清洗剂":["dishwashing","detergent"],
"水族箱（玻璃）":["water","tank","glass"],
"汤匙（塑料制）":["spoon","plastic"],
"汤匙（木制）":["spoon","wood"],
"汤匙（不锈钢制）":["spoon","stainless","steel"],
"章鱼小丸子机":["takoyaki","cooking","grill"],
"油画颜料":["oil","color"],
"彩色铅笔":["color","pencil"],
"墨水":["ink"],
"颜料":["painting","color"],
"卷笔刀":["pencil","sharpener"],
"折纸":["origami","paper"],
"替芯":["pen","rifill"],
"画轴":["scroll","painting"],
"盒式磁带":["cassette","tape"],
"图钉":["pushpin","thumbtack"],
"纸杯":["paper","cup"],
"纸袋":["paper","bag"],
"纸盘":["paper","plate"],
"透明文件夹":["clear","file"],
"夹子":["clip"],
"胶枪":["glue","gun"],
"蜡笔":["crayon"],
"橡皮":["eraser"],
"指南针":["compass","direction","magnet"],
"圆规":["compass","drafting","tool"],
"自动铅笔":["mechanical","pencil"],
"尺子":["ruler"],
"水性记号笔":["water","based","marker"],
"砚台":["ink","stone"],
"回形针":["paper","clip"],
"机油滤清器（汽车・摩托车用品）":["vehicle","oil","filter"],
"交流发电机":["vehicle","alternator"],
"汽车导航仪":["car","navigation","devices"],
"垫圈":["vehicle","gasket"],
"钥匙链":["key","chain"],
"冷凝器（汽车空调的冷却部件）":["vehicle","condenser"],
"鞍座":["saddle"],
"发电机（汽车部件）":["vehicle","generator"],
"弹簧（汽车部件・钢铁）":["vehicle","spring"],
"链轮":["vehicle","sprocket"],
"扰流板":["vehicle","spoiler"],
"链条":["vehicle","chain"],
"儿童安全座椅":["infant","car","seat"],
"摩托车车罩":["vehicle","covers"],
"框架":["vehicle","body","frame"],
"踏板":["pedal"],
"汽车用前照灯 汽车用尾灯":["car","headlight","car","taillight"],
"车轮（汽车）":["wheel","cars"],
"轮子（自行车）":["wheel","bicycles"],
"散热器":["vehicle","radiator"],
"调节器（汽车部件）":["vehicle","regulator"],
"贝壳装饰品":["shell","work"],
"画框":["picture","frame"],
"花瓶":["vase"],
"靠垫":["cushion"],
"钱包（其他材料）":["wallet","material"],
"相框":["picture","frame"],
"念珠（木制）":["rosary","wood"],
"念珠（石制）":["rosary","stone"],
"睡袋":["shrug"],
"西装（男式 其他纤维材料）":["suit","men","textile","materials"],
"西装（女式 其他纤维材料）":["suit","women","textile","materials"],
"水族箱（塑料）":["water","tank","plastic"],
"篷布":["tarp"],
"榻榻米":["tatami","mat"],
"包（布、纤维材料）":["bag","fabric","textile","material"],
"包（其他材料）":["bag","material"],
"手提包（布、纤维材料）":["handbag","fabric","textile","material"],
"手提包（其他材料）":["handbag","material"],
"毛毯":["blanket"],
"婴儿服（其他纤维材料）":["babywear","textile","materials"],
"小手包（布、纤维材料）":["pouch","bag","fabric","textile"],
"小手包（其他材料）":["pouch","bag","material"],
"垫子":["mat"],
"毛毯（亚克力）":["blanket","acrylic"],
"身高计":["stadiometer"],
"双目望远镜":["binoculars"],
"体温计":["thermometer"],
"体重计":["weighing","machine"],
"体成分监测仪":["body","composition","monitor"],
"量角器":["protractor"],
"吸奶器":["breast","pump"],
"茶泡饭":["ochazuke"],
"马铃薯淀粉":["potato","starch"],
"柴鱼花":["dried","bonito"],
"鱼糕":["kamaboko"],
"干海带":["dried","wakame","seaweed"],
"寒天":["agar","jelly"],
"葫芦条":["dried","gourd","shaving"],
"高筋面粉":["strong","flour"],
"冻豆腐":["freeze","dried","bean","curd"],
"大米粉":["rice","flour"],
"魔芋":["konjak","jelly","food"],
"盐辛（原材料为鱼）":["salted","fish","gut","fish"],
"盐辛（原材料为鱿鱼）":["salted","fish","gut","squid"],
"盐渍海带":["dried","salted","kelp"],
"糯米粉":["white","bean","flour"],
"荞麦粉":["buckwheat","flour"],
"日式高汤":["dashi","soup"],
"酵母粉":["dry","yeast"],
"薯蓣昆布（干海带丝）":["kelp","grated","yam"],
"海苔":["laver"],
"低筋面粉":["weak","flour"],
"羊栖菜":["hijiki","seaweed"],
"蛋白粉":["protein","powder"],
"味噌汤（速食）":["instant","miso","soup"],
"味噌腌菜":["miso","pickles"],
"蜂蜡":["beeswax"],
"和服（男式 其他纤维材料）":["kimono","costume","men","textile"],
"和服（女式 其他纤维材料）":["kimono","costume","women","textile"],
"袜子（其他纤维材料）":["socks","textile","materials"],
"毛线":["woolen","yarn"],
"大衣（男式 其他纤维材料）":["coat","men","textile","materials"],
"大衣（女式 其他纤维材料）":["coat","women","textile","materials"],
"内衣（男式 其他纤维材料）":["underwear","men","textile","materials"],
"内衣（女式 其他纤维材料）":["underwear","women","textile","materials"],
"运动服（男式 其他纤维材料）":["jersey","men","textile","materials"],
"运动服（女式 其他纤维材料）":["jersey","women","textile","materials"],
"茄克（男式 其他纤维材料）":["jacket","men","textile","materials"],
"茄克（女式 其他纤维材料）":["jacket","women","textile","materials"],
"衬衫（男式 其他纤维材料）":["shirt","men","textile","materials"],
"衬衫（女式 其他纤维材料）":["shirt","women","textile","materials"],
"汗衫（男式 其他纤维材料）":["undershirt","men","textile","materials"],
"汗衫（女式 其他纤维材料）":["undershirt","women","textile","materials"],
"运动外套（男式 其他纤维材料）":["windbreaker","men","textile","materials"],
"运动外套（女式 其他纤维材料）":["windbreaker","women","textile","materials"],
"披巾（其他纤维材料）":["shawl","textile","materials"],
"短裙（其他纤维材料）":["skirt","textile","materials"],
"方巾（其他纤维材料）":["scarf","textile","materials"],
"长裤（男式 其他纤维材料）":["pants","men","textile","materials"],
"长裤（女式 其他纤维材料）":["pants","women","textile","materials"],
"毛衣（男式 其他纤维材料）":["sweater","men","textile","materials"],
"毛衣（女式 其他纤维材料）":["sweater","women","textile","materials"],
"手套（其他纤维材料）":["gloves","textile","materials"],
"道服（男式 其他纤维材料）":["dogi","men","textile","materials"],
"道服（女式 其他纤维材料）":["dogi","women","textile","materials"],
"运动衫（男式 其他纤维材料）":["sweatshirt","men","textile","materials"],
"运动衫（女式 其他纤维材料）":["sweatshirt","women","textile","materials"],
"女式礼服（其他纤维材料）":["dress","textile","materials"],
"领带（其他纤维材料）":["tie","textile","materials"],
"连帽衫（男式 其他纤维材料）":["hoodie","men","textile","materials"],
"连帽衫（女式 其他纤维材料）":["hoodie","women","textile","materials"],
"和服外褂（男式 其他纤维材料）":["haori","coat","men","textile"],
"和服外褂（女式 其他纤维材料）":["haori","coat","women","textile"],
"袴（男式 其他纤维材料）":["hakama","pants","men","textile"],
"袴（女式 其他纤维材料）":["hakama","pants","women","textile"],
"睡衣（男式 其他纤维材料）":["pajama","men","textile","materials"],
"睡衣（女式 其他纤维材料）":["pajama","women","textile","materials"],
"手帕（其他纤维材料）":["handkerchief","textile","materials"],
"内裤（男式 其他纤维材料）":["underpants","men","textile","materials"],
"内裤（女式 其他纤维材料）":["underpants","women","textile","materials"],
"笔盒（纤维材料）":["pencil","case","textile","material"],
"女式罩衫（其他纤维材料）":["blouse","textile","materials"],
"背心（女式）":["vest","women","textile","materials"],
"背心（男式）":["vest","men","textile","materials"],
"围巾（其他纤维材料）":["scarf","textile","materials"],
"棉线":["cotton","yarn"],
"丧服（男式 其他纤维材料）":["mourning","clothes","men","textile"],
"丧服（女式 其他纤维材料）":["mourning","clothes","women","textile"],
"股引（日式细筒裤、秋裤、棉裤）（男式 其他纤维材料）":["long","underwear","men","textile"],
"股引（日式细筒裤、秋裤、棉裤）（女式 其他纤维材料）":["long","underwear","women","textile"],
"浴衣（男式 其他纤维材料）":["light","kimono","costume","men"],
"浴衣（女式 其他纤维材料）":["light","kimono","costume","women"],
"制服（男式 其他纤维材料）":["uniform","men","textile","materials"],
"制服（女式 其他纤维材料）":["uniform","women","textile","materials"],
"高叉连体衣（男式 其他纤维材料）":["leotard","men","textile","materials"],
"高叉连体衣（女式 其他纤维材料）":["leotard","women","textile","materials"]
};
function stripBrandName(text: string): string {
  let c = text.replace(/[A-Za-z0-9\s\-]+牌/g,"").replace(/^[A-Za-z0-9\s\-]+(?=[\u4e00-\u9fff])/g,"");
  c = c.replace(/^[A-Z][a-z]+\s+/,""); return c.trim();
}

function extractHsKeywords(text: string): string[] {
  const desc = text.replace(/[\u4e00-\u9fff]/g," ");
  return desc.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(w => w.length>2 && !["the","and","for","not","are","was","has","its","any","with","from","this","that","have","been","other","than","which","each","will","into","such","also","more","some","all","but","can","did","get","got","had","her","him","his","how","may","new","now","off","old","one","our","out","own","per","put","say","set","she","too","use","via","way","who","yet"].includes(w));
}

export function extractKeywords(text: string): string[] {
  const result: string[] = []; const cleaned = stripBrandName(text);
  const addWord = (w: string) => { if(result.includes(w)) return; result.push(w); const s = SYNONYM_MAP[w]; if(s) for(const x of s) { if(x!==w && !result.includes(x)) result.push(x); } };
  const cnTerms = cleaned.match(/[\u4e00-\u9fff]{2,}/g) || [];
  for(const term of cnTerms) {
    const en = CN_MAP[term];
    if(en) { addWord(term); for(const ek of en) addWord(ek); }
    else { let found=false; for(const [cKey,eTerms] of Object.entries(CN_MAP)) { if(term.includes(cKey) && cKey.length>=1) { addWord(cKey); for(const ek of eTerms) addWord(ek); found=true; } } if(!found && term.length<=10 && !result.includes(term)) result.push(term); }
  }
  const enPart = cleaned.replace(/[\u4e00-\u9fff]/g," ");
  const latinWords = enPart.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(w => w.length>2 && !["the","and","for","not","are","was","has","its","any","with","from","this","that","have","been","other","than","which","each","will","into","such","also","more","some","all","but","can","did","get","got","had","her","him","his","how","may","new","now","off","old","one","our","out","own","per","put","say","set","she","too","use","via","way","who","yet"].includes(w));
  for(const w of latinWords) { if(/^[a-z]*\d+[a-z]*$/.test(w) && w.length>3) continue; addWord(w); }
  return result;
}

function trigramSimilarity(a:string,b:string):number {
  if(a===b)return 1; if(a.length<3||b.length<3)return 0;
  const tg=(s:string)=>{const set=new Set<string>();for(let i=0;i<=s.length-3;i++)set.add(s.substring(i,i+3));return set;};
  const ta=tg(a),tb=tg(b);let o=0;for(const t of ta){if(tb.has(t))o++;}return o/Math.max(ta.size,tb.size);
}

function scoreMatch(desc:string[],target:string[]):number {
  let s=0;for(const d of desc){let b=0;for(const t of target){
    if(t===d){b=Math.max(b,1);continue;}
    if(t.includes(d)){b=Math.max(b,0.7+0.3*d.length/t.length);continue;}
    if(d.includes(t)){const r=Math.min(d.length,t.length)/Math.max(d.length,t.length);if(r>=0.6)b=Math.max(b,0.6+0.2*r);continue;}
    const sim=trigramSimilarity(d,t);if(sim>0.45)b=Math.max(b,0.3+0.4*sim);
  }s+=b;}return s;
}

function computeMatchedKeywords(desc:string[],targetDesc:string):string[] {
  const tk=extractHsKeywords(targetDesc); const m:string[]=[];
  for(const d of desc){let b=0;for(const t of tk){
    if(t===d){b=Math.max(b,1);continue;}
    if(t.includes(d))b=Math.max(b,0.7+0.3*d.length/t.length);
    else if(d.includes(t)){const r=Math.min(d.length,t.length)/Math.max(d.length,t.length);if(r>=0.6)b=Math.max(b,0.5);}
    else{const sim=trigramSimilarity(d,t);if(sim>0.45)b=Math.max(b,0.3+0.4*sim);}
  }if(b>0.3)m.push(d);}return m;
}

export async function matchDescription(hsCode:string,description:string):Promise<HsCodeMatchResult>{
  const l=validateHsCode(hsCode);
  if(!l.valid||!l.description){const cd=lookupHsCode(hsCode)?.description||null;return{matched:false,confidence:"unknown",detail:`HS ${hsCode} not in DB`,suggestions:[],suggested_description:cd};}
  const hk=extractHsKeywords(l.description),dk=extractKeywords(description);
  if(!dk.length)return{matched:true,confidence:"unknown",detail:"too short",suggestions:[],suggested_description:l.description};
  const ms=scoreMatch(dk,hk),ratio=dk.length>0?ms/dk.length:0;
  if(ratio>=0.4)return{matched:true,confidence:ratio>=0.6?"exact":"partial",detail:ratio>=0.6?"match":"similar",suggestions:[],suggested_description:ratio>=0.6?null:l.description};
  if(ratio>=0.2)return{matched:true,confidence:"partial",detail:"partial match",suggestions:[],suggested_description:l.description};
  const llm=await classifyWithLlm(description);
  if(llm&&llm.candidates.length>0){
    const ls:SuggestionEntry[]=llm.candidates.map((c:any)=>({code:c.code,description:c.description,description_cn:c.description_cn||c.description,confidence:c.confidence,matched_keywords:c.matched_keywords||[]}));
    const ucc=l.code.replace(/[.\-\s]/g,""),lm=llm.candidates.find((c:any)=>c.code.substring(0,6)===ucc.substring(0,6));
    if(lm&&lm.confidence>=0.6)return{matched:true,confidence:"exact",detail:"LLM verified",suggestions:[],suggested_description:lm.description};
    if(lm&&lm.confidence>=0.3)return{matched:true,confidence:"partial",detail:"LLM partial",suggestions:ls.filter((s:SuggestionEntry)=>s.code.substring(0,6)!==ucc.substring(0,6)).slice(0,2),suggested_description:lm.description};
    return{matched:false,confidence:"mismatch",detail:"mismatch",suggestions:ls,suggested_description:ls[0]?.description||null};
  }
  const db=getHistoryDb();
  const ar=db.prepare("SELECT code,description FROM hs_codes WHERE level>=4 ORDER BY code LIMIT 2000").all() as HsCodeEntry[];
  const sc:{code:string;description:string;score:number;sameChapter:boolean}[]=[];
  for(const r of ar){if(r.code===l.code)continue;const s=scoreMatch(dk,extractHsKeywords(r.description));if(s>0)sc.push({code:r.code,description:r.description,score:s,sameChapter:r.code.substring(0,2)===l.chapter});}
  sc.sort((a,b)=>{if(a.sameChapter!==b.sameChapter)return a.sameChapter?1:-1;return b.score-a.score;});
  const sg=sc.slice(0,3).map(s=>({code:s.code,description:s.description,description_cn:"",confidence:Math.min(s.score/Math.max(dk.length,1),1),matched_keywords:computeMatchedKeywords(dk,s.description)}));
  return{matched:false,confidence:"mismatch",detail:"mismatch",suggestions:sg,suggested_description:sg.length>0?sg[0].description:null};
}

export async function suggestHsCodes(description:string):Promise<SuggestionEntry[]>{
  const llm=await classifyWithLlm(description);
  if(llm&&llm.candidates.length>0)return llm.candidates.map((c:any)=>({code:c.code,description:c.description,description_cn:c.description_cn||c.description,confidence:c.confidence,matched_keywords:c.matched_keywords||[]}));
  const dk=extractKeywords(description);if(!dk.length)return[];
  const db=getHistoryDb();
  const ar=db.prepare("SELECT code,description FROM hs_codes WHERE level>=4 ORDER BY code LIMIT 2000").all() as HsCodeEntry[];
  const sc:{code:string;description:string;score:number}[]=[];
  for(const r of ar){const s=scoreMatch(dk,extractHsKeywords(r.description));if(s>0)sc.push({code:r.code,description:r.description,score:s});}
  sc.sort((a,b)=>b.score-a.score);
  return sc.slice(0,5).map(s=>({code:s.code,description:s.description,description_cn:"",confidence:Math.min(s.score/Math.max(dk.length,1),1),matched_keywords:computeMatchedKeywords(dk,s.description)}));
}

export function getChapterInfo(chapter:string):{section:string;description:string}|null{
  const db=getHistoryDb();const r=db.prepare("SELECT section,description FROM hs_codes WHERE code=? AND level=2").get(chapter) as HsCodeEntry|undefined;
  return r?{section:r.section,description:r.description}:null;
}
